### ISSUE TITLE
Error while converting pcd to depth image

### ISSUE THREAD

**Issue by Pranav24-8** [dougsm/ggcnn#19]
Hi,
I am getting this error while converting pcd to depth image using generate_cornell_depth.py.

```bash
OpenCV Error: Unsupported format or combination of formats (Only 8-bit 1-channel and 3-channel input/output images are supported) in cvInpaint, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/photo/src/inpaint.cpp, line 751
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pranav/GRASPING/ggcnn/utils/dataset_processing/generate_cornell_depth.py", line 19, in <module>
    di.inpaint()
  File "/home/pranav/GRASPING/ggcnn/utils/dataset_processing/image.py", line 185, in inpaint
    self.img = cv2.inpaint(self.img, mask, 1, cv2.INPAINT_NS)
cv2.error: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/photo/src/inpaint.cpp:751: error: (-210) Only 8-bit 1-channel and 3-channel input/output images are supported in function cvInpaint
```
Please help.

**Comment by dougsm** [comment]
Hi,
Inpainting of float-valued arrays is only supported in opencv version >=3.3.0. Looks like you have version 3.2. Try upgrading to a newer opencv version.

**Comment by Pranav24-8** [comment]
It works in opencv version 4.1.2. Thank you for the help.
